name: Build PR
# Builds and runs tests on each push to a branch PR'ed against main.

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'design/**'
      - 'planning/**'
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install abigen
        run: |
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install ethereum

      - name: Install dependencies
        run: cd contracts && npm install
      - name: Hardhat test
        run: cd contracts && npx hardhat generate-abi-bindings --output-dir generated
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      # Makes sure the artifacts are built correctly
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test --failfast -v ./... -count=1
        env:
          USE_GETH_BINARY: true

      - name: Store simulation logs
        uses: actions/upload-artifact@v3
        with:
          name: ci-logs
          path: |
            integration/.build/simulations/sim-log-*.txt
            integration/.build/noderunner/noderunner-*.txt
            integration/.build/wallet_extension/wal-ext-*.txt
            integration/.build/eth2/*
        if: always() # Ensures the artifacts are created even if the tests fail.
